// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"mowa-backend/api/controller"
	"mowa-backend/api/services"
)

// Injectors from injector.go:

func InitializeUserController() controller.UserController {
	userService := services.NewUserService()
	userController := controller.NewUserController(userService)
	return userController
}

func InitializeAdminController() controller.AdminController {
	adminService := services.NewAdminService()
	adminController := controller.NewAdminController(adminService)
	return adminController
}
