// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard.sql

package db

import (
	"context"
)

const getStatistics = `-- name: GetStatistics :one
SELECT COUNT(*) AS total_users FROM users
`

func (q *Queries) GetStatistics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStatistics)
	var total_users int64
	err := row.Scan(&total_users)
	return total_users, err
}
